package org.puj.ingesoft.views;


public enum NombrePantallas {
    INICIO,
    MENU_PACIENTE,
    INICIO_AFILIADO,
    INICIO_GENERAL,
    INICIO_MEDICO,
    REGISTRO_GENERAL,
    REGISTRO_MEDICO,
    REGISTRO_PACIENTE,
    CITAS_EXISTENTES,
    CONFIRMAR_CITA,
    DISPONIBILIDAD,
    GESTIONAR_CITA,
    REPROGRAMAR_CITA,
    MENU_MEDICO,
    CITAS_AGENDADAS,
    CREAR_HISTORIAL_CLINICO,
    ENTRADA_CLINICA,
    VER_HISTORIAL_CLINICO,
    LABORATORIOCLINICO,
    REMISION,
    VER_ENTRADA_CLINICA,
    VER_MEDICAMENTOS,
    ORIENTACION,
    CARRITO,
    PAGOS_GENERAL,
    PAGAR,
    PQRS;
}